export const dummyTableData: { [key: string]: any }[] = [
  {
    id: 1,
    name: "Brand",
    createdAt: "2024-10-01",
    acquired: 66,
    engagedAndUnique: "50/20",
    platform: "X",
    conversion: "10%",
  },
  {
    id: 2,
    name: "Group",
    createdAt: "2024-10-03",
    acquired: 66,
    engagedAndUnique: "50/20",
    platform: "Instagram",
    conversion: "10%",
  },
  {
    id: 3,
    name: "Security",
    createdAt: "2024-10-04",
    acquired: 66,
    engagedAndUnique: "50/20",
    platform: "Instagram",
    conversion: "10%",
  },
  {
    id: 4,
    name: "Solutions",
    createdAt: "2024-10-06",
    acquired: 66,
    engagedAndUnique: "50/20",
    platform: "Instagram",
    conversion: "10%",
  },
  {
    id: 5,
    name: "Applications",
    createdAt: "2024-10-07",
    acquired: 66,
    engagedAndUnique: "50/20",
    platform: "LinkedIn",
    conversion: "10%",
  },
  {
    id: 6,
    name: "Quality",
    createdAt: "2024-10-08",
    acquired: 66,
    engagedAndUnique: "50/20",
    platform: "Instagram",
    conversion: "10%",
  },
  {
    id: 7,
    name: "Implementation",
    createdAt: "2024-10-11",
    acquired: 66,
    engagedAndUnique: "50/20",
    platform: "Facebook",
    conversion: "10%",
  },
  {
    id: 8,
    name: "Integration",
    createdAt: "2024-10-12",
    acquired: 66,
    engagedAndUnique: "50/20",
    platform: "Instagram",
    conversion: "10%",
  },
  {
    id: 9,
    name: "Intranet",
    createdAt: "2024-10-14",
    acquired: 66,
    engagedAndUnique: "50/20",
    platform: "Instagram",
    conversion: "10%",
  },
  {
    id: 10,
    name: "Group",
    createdAt: "2024-10-30",
    acquired: 66,
    engagedAndUnique: "50/20",
    platform: "Instagram",
    conversion: "10%",
  },
  {
    id: 11,
    name: "Branding",
    createdAt: "2024-11-01",
    acquired: 66,
    engagedAndUnique: "50/20",
    platform: "Instagram",
    conversion: "10%",
  },
];
